CREATE TABLE PROBLEM(
  PID INT PRIMARY KEY,
  TITLE TEXT,
  DESCRIPTION TEXT,
  DIFF VARCHAR(1),
  INPUT TEXT,
  OUTPUT TEXT,
  AUTHOR VARCHAR(20),
  TIME_LIMIT INT,
  MEMORY_LIMIT INT,
  CASE_COUNT INT,
  ACCEPT INT,
  TOTAL INT,
  GMT_CREATED DATE,
  GMT_MODIFIED DATE
);