CREATE TABLE SUBMIT(
  RID INT PRIMARY KEY AUTO_INCREMENT,
  PID INT,
  UID INT,
  CODE TEXT,
  LANGUAGE VARCHAR(10),
  STATUS INT,
  RUN_TIME INT,
  RUN_MEMORY INT,
  COMPILATION_MESSAGE TEXT,
  GMT_CREATED DATE,
  GMT_MODIFIED DATE,
  CONSTRAINT FOREIGN KEY (PID) REFERENCES PROBLEM(PID),
  CONSTRAINT FOREIGN KEY (UID) REFERENCES USER(ID)
);
